version: incident/v1
id: 07vyh9fwq8sb
name: Hosted Grafana Outage (prod-us-west-0)
impact: critical
systems:
    - 8wq97lhx59x7
timeline:
    - ts: "2025-07-03 22:17:26"
      description: |-
        As of 21:27 UTC, we identified a DNS-related issue affecting the prod-us-west-0 cluster. This may result in a full outage of Hosted Grafana services for impacted users.

        Our engineering team is actively investigating and working to resolve the issue. We will share updates as they become available.
      investigating: true
    - ts: "2025-07-03 22:28:16"
      description: Engineering has released a fix and as of 22:20 UTC, customers should no longer experience any issues. At this time, we are considering this issue resolved. No further updates.
      resolved: true
