version: incident/v1
id: 2q65c3lvfvj0
name: API offline in GCP Singapore (prod-ap-southeast-0) and GCP Brazil (prod-sa-east-0)
impact: none
systems:
    - zp7h7t53k0jn
    - 4whxks101kq7
timeline:
    - ts: "2025-04-27 18:48:05"
      description: The synthetics API is currently offline in both GCP Singapore (prod-ap-southeast-0) and GCP Brazil (prod-sa-east-0).  We are investigating the issue.
      investigating: true
