version: incident/v1
id: 2q65c3lvfvj0
name: API offline in GCP Singapore (prod-ap-southeast-0) and GCP Brazil (prod-sa-east-0)
impact: none
systems:
    - zp7h7t53k0jn
    - 4whxks101kq7
timeline:
    - ts: "2025-04-27 18:48:05"
      description: The synthetics API is currently offline in both GCP Singapore (prod-ap-southeast-0) and GCP Brazil (prod-sa-east-0).  We are investigating the issue.
      investigating: true
    - ts: "2025-04-27 19:52:19"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2025-04-27 20:28:56"
      description: API came online again at 19:14 UTC in GCP Singapore and 19:21 UTC in GCP Brazil.  While the API was unavailable, probes were unaffected.  Synthetic monitoring checks in all probes continued to run and publish data during this incident.  The incident was caused by earlier database maintenance in these regions.
      resolved: true
