version: incident/v1
id: 3rqk10z0jlr1
name: K6 - Cloud test-run issues
impact: minor
systems:
    - m79yjv169r06
timeline:
    - ts: "2026-08-01 07:25:38"
      description: We are currently investigating an issue which is resulting in some test runs to abort and metrics data to be incomplete for a subset of tests
      investigating: true
