version: incident/v1
id: 6fdsld9f0nsn
name: Rule evaluation error on cluster prod-gb-south-0
impact: minor
systems:
    - 7vr04qdqjtn6
timeline:
    - ts: "2026-06-29 10:34:06"
      description: We are currently investigating Rule Evaluation errors on the cluster prod-gb-south-0 which is leading to error codes showing within the stacks. We are looking into the issue and will update accordingly.
      investigating: true
    - ts: "2026-06-29 11:14:22"
      description: A fix has been applied and we are currently monitoring results.
    - ts: "2026-06-29 13:12:07"
      description: This incident has been resolved.
      resolved: true
