version: incident/v1
id: 6z7f53fhxy43
name: Not possible to create stacks on prod-us-west-0
impact: minor
systems:
    - 8wq97lhx59x7
timeline:
    - ts: "2025-03-26 13:39:07"
      description: "We are experiencing issues with stack creation in the prod-us-west-0  region. \n\nAdding and removing plugins are impacted as well"
      investigating: true
