version: incident/v1
id: 82b7fqv2pgk2
name: Authentication errors in Grafana Cloud
impact: critical
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - hl40gbs2zkn4
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
timeline:
    - ts: "2025-10-08 15:31:49"
      description: We are investigating reports that authentication errors are causing delays or failures across Grafana Cloud. This could impact API tokens and sending telemetry. We will update this post with more information as it becomes available.
      investigating: true
    - ts: "2025-10-08 15:42:18"
      description: The issue has been identified. Our engineering teams are actively working on mitigation & resolution for all customers.
    - ts: "2025-10-08 15:45:26"
      description: For affected customers, dashboards and panels in Grafana Cloud might return an error. We're still actively working to resolve this as soon as possible.
    - ts: "2025-10-08 16:00:55"
      description: A fix has been implemented, and we are monitoring the results.
    - ts: "2025-10-08 17:01:59"
      description: This incident has been resolved.
      resolved: true
