version: incident/v1
id: 83c6fz4phfkl
name: Loki degraded writes in SouthEast region
impact: none
systems:
    - dy7xwydh5kv3
timeline:
    - ts: "2025-10-13 13:32:21"
      description: "Cloud Logs region experienced degraded writes between 11:38-12:20 UTC. \nThe incident is mitigated for now and we are monitoring the situation."
    - ts: "2025-10-13 13:32:58"
      description: We are continuing to monitor for any further issues.
