version: incident/v1
id: 8fsjclrbw7b5
name: Some elevated error rates on the prometheus-blocks-prod-us-central1, influx-blocks-prod-us-central1 and graphite-blocks-prod-us-central1 clusters.
impact: minor
systems:
    - jhc34sjt42wd
timeline:
    - ts: "2025-10-05 08:03:25"
      description: It seems that the cloud provider object storage has latency spikes, which directly affect our write latency.
      investigating: true
    - ts: "2025-10-05 09:07:29"
      description: We are continuing to investigate this issue.
      investigating: true
    - ts: "2025-10-05 11:39:57"
      description: We have observed marked improvement with the issue. Customers should no longer experience this issue. We will continue to monitor and provide updates.
    - ts: "2025-10-05 13:37:55"
      description: We continue to observe a period of recovery. At this time, we are considering this issue resolved.
      resolved: true
