version: incident/v1
id: 8w73thd13w87
name: Grafana Cloud Partial Outage
impact: major
systems:
    - hbqgpzmf8h9k
timeline:
    - ts: "2024-09-27 05:13:52"
      description: We are aware of issues with Grafana Cloud services in the prod-us-east-0 region and are currently investigating.
      investigating: true
    - ts: "2024-09-27 06:08:10"
      description: This has been stable as of 05:27 UTC and we are continuing to monitor.
