version: incident/v1
id: 91n91dr0dg6x
name: Cloud Log Exporter Unavailable
impact: major
systems:
    - 1cj80yl7f6dy
    - 9z18xdj3j8c7
    - gx6m1v8jy475
    - 318npch70m7f
    - nfll10wmx61f
    - dy7xwydh5kv3
    - 6rlxmdg0t6v3
    - c325hr67bhtb
    - hqf81r9207h6
    - 2gj2jt684k11
    - rwvs9fvrnhp2
    - x40g7bxm0q2d
    - v3g3j6krw8rp
    - gp2m13gyj6x2
    - 662yyglvgqpm
timeline:
    - ts: "2026-07-21 18:43:33"
      description: Cloud Log Exporter is temporarily not available in the marked regions. We are currently investigating this issue and will update as soon as we have more info to share.
      investigating: true
    - ts: "2026-07-21 20:04:09"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2026-07-21 21:06:15"
      description: This incident has been resolved.
      resolved: true
