version: incident/v1
id: b6yc10yk8kv7
name: Longer than expected load times in multiple AWS regions
impact: major
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2025-02-24 18:26:34"
      description: |-
        Engineering has identified the issue and is currently exploring remediation options. At this time, users may experience instances taking 15+ minutes to come off the "Grafana is Loading" page.

        We will continue to provide updates as more information is shared.
    - ts: "2025-02-24 19:59:01"
      description: Engineering has released a fix, and customers should no longer be experiencing this issue. We will continue to monitor for recurrence and provide updates accordingly.
    - ts: "2025-02-24 22:22:37"
      description: "Our Engineering team has identified that https://status.grafana.com/incidents/q6k82s6s7sj0 is related to this issue. \nAt this moment we keep monitoring our services. We'll be providing further updates accordingly."
    - ts: "2025-02-26 15:39:00"
      description: We are continuing to monitor for further issues. The issue is scoped to AWS and is only significantly observed in the prod-us-east-0 and prod-eu-west-2 regions. We have also retroactively changed the title of this status to accurately reflect the scope.
    - ts: "2025-02-26 21:35:01"
      description: We are seeing this issue occur in multiple AWS regions. Our engineering team is currently engaged in remediating this issue.
    - ts: "2025-02-28 18:26:28"
      description: Our engineering team is still investigating the root cause of the issue and has taken temporary measures to alleviate the impact on customers. We will continue to provide updates as more information becomes available.
    - ts: "2025-03-05 16:02:52"
      description: Our engineering team has taken temporary measures to alleviate the impact on customers. We will continue to provide updates as more information becomes available.
    - ts: "2025-03-05 23:27:37"
      description: This incident has been resolved.
      resolved: true
