version: incident/v1
id: bj98jxql3cpl
name: Error Creating Teams
impact: minor
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
timeline:
    - ts: "2025-04-09 12:48:01"
      description: We are currently investigating an issue where some customers are unable to create a new Team in Grafana Cloud.
    - ts: "2025-04-09 13:54:07"
      description: The issue has been identified, and we are in the process of rolling out a fix.
    - ts: "2025-04-10 08:02:29"
      description: The fix has been rolled out and at this time, we are considering this resolved.
      resolved: true
