version: incident/v1
id: d1hcb2xk4hzl
name: Load test metrics not being ingested during execution
impact: major
systems:
    - m79yjv169r06
    - wbhrnd130mb0
timeline:
    - ts: "2025-05-16 17:14:39"
      description: We are currently investigating this issue.
      investigating: true
    - ts: "2025-05-16 17:59:42"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2025-05-16 18:00:29"
      description: We are continuing to monitor for any further issues.
    - ts: "2025-05-16 18:09:05"
      description: This incident has been resolved.
      resolved: true
