version: incident/v1
id: d48jb3ksf3fc
name: Issues with new stack creation
impact: minor
systems:
    - m0qkgdzwyr6l
timeline:
    - ts: "2024-11-18 23:46:34"
      description: We are currently investigating issues with creation of new stacks.
      investigating: true
    - ts: "2024-11-19 01:40:30"
      description: A fix has been implemented and we are monitoring the results.
    - ts: "2024-11-19 02:08:30"
      description: This incident has been resolved.
      resolved: true
