version: incident/v1
id: dhc9kbd7bfz7
name: 'Grafana Cloud: SAML UI Role Mapping'
impact: minor
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2025-04-01 18:14:38"
      description: "As of 18:00 UTC, we became aware of an issue with the Grafana Cloud SAML UI. Users experiencing this issue may encounter not being able to successfully save any role mapping changes. \n\nEngineering is actively engaged and assessing the issue. We will provide updates accordingly."
      investigating: true
    - ts: "2025-04-01 22:45:11"
      description: |-
        Engineering has identified the issue and are currently implementing remediation.

        We will continue to provide updates as more information is shared.
    - ts: "2025-04-02 06:32:52"
      description: Engineering has released a fix and as of 0600 UTC, customers should no longer experience the inability to change SAML role mapping. At this time, we are considering this issue resolved. No further updates.
      resolved: true
