version: incident/v1
id: dhhbnp7ct8m1
name: Issues on Stack creation
impact: minor
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - hl40gbs2zkn4
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - v2sp8gjnhwk6
    - lxb7122px698
    - b562z2mrff79
    - fs80tlfpb7kx
    - h1t1253xs6k9
    - 1mnpb5g27m21
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
    - 4sk1vxpqgb7s
timeline:
    - ts: "2026-04-16 12:52:01"
      description: |-
        Since today 16th at ~12:11UTC we are seeing issues on stack creation across all our regions. Customers will experience error message when attempting to create a stack.
        Our engineering team has identified the source of the issue as external to Grafana (provider), and they are tracking its recovery.
    - ts: "2026-04-16 13:19:58"
      description: The issue is fixed and we are currently monitoring the service.
