version: incident/v1
id: f4ngcp5y2r4t
name: K6 Sporadic DNS Issues
impact: minor
systems:
    - m79yjv169r06
timeline:
    - ts: "2026-04-14 09:22:32"
      description: We are having sporadic DNS issues that occasionally affect the start of cloud test runs, causing them to abort. We are currently working to resolve. The issue has been occurring since April 9.
    - ts: "2026-04-14 14:29:15"
      description: We’ve implemented a fix and are monitoring the results to confirm the issue is fully resolved. Services may start to recover during this time.
    - ts: "2026-04-14 14:29:22"
      description: Our engineering team has deployed a fix and we are currently monitoring the behaviour of the system until full resolution.
    - ts: "2026-04-15 12:59:23"
      description: This incident is now resolved. We had intermediary issues with a flaky DNS server that caused random tests to not start properly. Since the DNS server was fixed, we haven't been seeing the issue anymore.
      resolved: true
