version: incident/v1
id: fb95xlbs3vxy
name: IRM (OnCall + Incident) plugin not available
impact: critical
systems:
    - 1mxpk7q1bkb6
    - h3wg1km0qxwv
timeline:
    - ts: "2025-07-15 12:10:21"
      description: After the latest plugin update we have identified an issue with the IRM plugin making this one unavailable across Grafana Hosted instances. We are actively working to restore the service.
      investigating: true
    - ts: "2025-07-15 12:15:47"
      description: We are continuing to investigate this issue.
      investigating: true
    - ts: "2025-07-15 12:42:57"
      description: Our team has identified the root cause of the issue and is applying measurements to restore the service. This one should be restored again shortly.
    - ts: "2025-07-15 14:42:51"
      description: After the performed mitigation, we are seeing normal functioning again of the IRM plugin module. We are still monitoring the service until full health.
    - ts: "2025-07-15 18:52:30"
      description: This incident has been resolved.
      resolved: true
