version: incident/v1
id: g1jk56qqvvtm
name: New instance creation taking longer than expected
impact: minor
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2025-02-25 22:27:41"
      description: |-
        As of 2203 UTC, we became aware of an issue with creating new instances. Users experiencing this issue may encounter login loop or a failed login for a few minutes prior to the instance becoming completely available.

        Engineering is actively engaged and assessing the issue. We will provide updates accordingly.
      investigating: true
