version: incident/v1
id: g1xwkr6fl5c1
name: New and recently unpaused/unarchived Grafana Cloud instances unable to start.
impact: major
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
timeline:
    - ts: "2024-10-30 11:11:50"
      description: Users may see slower startup times for new, or previously inactive Grafana Cloud instances in all clusters. We're currently investigating the issue.
      investigating: true
    - ts: "2024-10-30 12:21:30"
      description: We identified the issue and applied the fix. We're currently monitoring the situation - there should be no issue with creating and unpausing/unarchiving instances anymore.
    - ts: "2024-10-30 15:28:55"
      description: The incident has been resolved. We applied an update to all Grafana Cloud instances, which inadvertently restarted instances regardless of whether they were active or not. This caused heavy load on our control plane, causing slower startup times.
      resolved: true
