version: incident/v1
id: hwrtblqx3jhm
name: Unable to Edit Notification Policies
impact: minor
systems:
    - tzt37d0skmyd
    - 3pxb2s9gd3qk
    - y2fvl0w81hnk
    - kckd7qfk2gql
    - 2xrvqwtmgk1j
    - qr8ttrr50lnd
    - 4vcmfvslpghq
    - fgtp31zqpw8v
    - 57jn84fvz98t
    - vcfc8qc5zj9n
    - y5ymzvw0c99f
    - p932bbpwynd4
    - tgt3hljzszy8
    - tfcmnh8pbnh9
    - hd6qyr8hc0yt
    - 5shpb4hb9xd1
    - ybvy0jrqz78d
    - x2sf2zvf07cy
timeline:
    - ts: "2026-04-07 15:17:47"
      description: We’re currently investigating an issue affecting notification policies. Our team is actively working to identify the cause and will share an update within 2 hours. Thank you for your patience.
      investigating: true
    - ts: "2026-04-07 16:52:54"
      description: We’ve identified the cause of the issue impacting notification policies. Our team is currently implementing a fix. We’ll provide another update in 2 hours or sooner if the situation changes.
    - ts: "2026-04-07 18:03:18"
      description: We’ve identified the cause of the issue impacting notification policies. Our team is currently implementing a fix. We’ll provide another update in 2 hours or sooner if the situation changes.
