version: incident/v1
id: njlc6q6c0kj8
name: High query latency for hosted Prometheus datasources
impact: none
systems:
    - 5270kl9kd6l2
timeline:
    - ts: "2025-06-20 15:48:59"
      description: |-
        Starting at 13:23 UTC and resolved at 13:36 UTC, some hosted Prometheus datasources experience high query latency, which could trigger false alarms or cause timeouts in the UI when querying.
        The root cause is being investigated.
      investigating: true
