version: incident/v1
id: q6k82s6s7sj0
name: New Instances failing to create across all regions.
impact: major
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2025-02-24 17:45:24"
      description: We are currently investigating an incident that is causing users to experience issues when creating new instances across all regions.
      investigating: true
    - ts: "2025-02-24 20:01:48"
      description: Engineering has released a fix, and customers should no longer be experiencing this issue. We will continue to monitor for recurrence and provide updates accordingly.
    - ts: "2025-02-24 22:16:13"
      description: |-
        Our Engineering team has identified that this issue is related to: https://status.grafana.com/incidents/b6yc10yk8kv7
        We'll be marking this incident as resolved and will provide updates for this event as well in the status page mentioned above.
      resolved: true
