version: incident/v1
id: qtyr8z0s4t59
name: Some Instances in prod-us-east-0 Experienced Issues Accessing Their Instance.
impact: none
systems: []
timeline:
    - ts: "2025-04-29 15:09:23"
      description: At approximately 14:20 UTC we observed an issue that caused some deployments in prod-us-east-0 to experience long load times, or issues accessing their instance. The issue was resolved shortly before 15:00 UTC.
      resolved: true
