version: incident/v1
id: qxdjf2wxrkz2
name: Zabbix plugin issue with failing connections.
impact: major
systems:
    - wfc1hb7m917l
    - 9zgd4n4s874v
    - zvfc1jlr92kg
    - 6wgslg1s3bzr
    - wdcnfc3drb8s
    - 2vj35rbpdr7s
    - nrv6vyr5l7m8
    - y8p2jm7hpwy0
    - tv6d4zqb6nz7
    - hbqgpzmf8h9k
    - t0592d5sxhgh
    - 8wq97lhx59x7
    - 1mnpb5g27m21
    - fs80tlfpb7kx
    - sc8qqdx6j1h5
    - c66zgq8xld33
    - kw9wxv34yw80
    - bh5f9ggjnj60
    - 54tht9mpb5sk
    - yt6pjkj14lvk
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 4vfjcc6ptw32
timeline:
    - ts: "2025-01-30 12:03:08"
      description: We've detected an issue with Zabbix plugin having problems with failing connections, making it unable to query and connect. We're investigating the issue.
      investigating: true
    - ts: "2025-01-30 12:31:28"
      description: The fix has been deployed and the issue appears to be fixed. We're monitoring to make sure that no further problems appear.
