version: incident/v1
id: r1trmnqpq2fn
name: Grafana Cloud Portal Accessibility Issues
impact: none
systems:
    - m0qkgdzwyr6l
timeline:
    - ts: "2024-11-18 10:47:43"
      description: |-
        We experienced an issue affecting access to Grafana Cloud portal. Our team has identified the root cause and deployed a fix. We are actively monitoring the situation to ensure the issue is fully resolved.

        If you encounter any further difficulties, please reach out to our support team. We apologize for the inconvenience and thank you for your patience.
