version: incident/v1
id: s2n42fdpm987
name: 'k6: Operational issue'
impact: major
systems:
    - 3gvy1n7fg4x4
    - m79yjv169r06
    - wbhrnd130mb0
    - z9074fpyx6sb
    - 236539c2nt69
    - qwkkscbddtdw
    - 8n34hh3y2yd0
timeline:
    - ts: "2024-10-07 20:03:04"
      description: Our cloud provider is currently experiencing issues. These may cause tests to abort or errors using the UI.
