version: incident/v1
id: swkfxkf1z0vy
name: Read and write path outage in Hosted Logs ap-south-1 region cells.
impact: critical
systems:
    - 318npch70m7f
timeline:
    - ts: "2025-07-03 09:23:53"
      description: We faced an issue with cells in ap-south-1 Hosted Logs region. Between 8:55 and 9:07 UTC this region faced the complete read and write paths outage. Since then it fully recovered and services are fully operational again. We're investigating the root cause right now.
      investigating: true
    - ts: "2025-07-03 10:09:59"
      description: We're currently monitoring health of the cluster since the outage was resolved and the issue was identified.
    - ts: "2025-07-03 10:10:07"
      description: Cluster fully operational.
    - ts: "2025-07-03 14:31:28"
      description: The incident was caused by multiple ingesters being unavailable at the same time due to moving ingester pods between nodes. It's a regular operation, but in this particular case the ingester took an unexpected long time to restart which coincided with another ingester eventually restarting at the same time, causing an issue.
      resolved: true
