version: incident/v1
id: tvyw8wf62g31
name: Loki write instability in prod-eu-west-2.loki-prod-012
impact: none
systems: []
timeline:
    - ts: "2026-04-14 12:02:23"
      description: There was a period of write instability yesterday. It was between ~1330 -1730 UTC yesterday.  This was due to a scheduled maintenance.
      resolved: true
