version: incident/v1
id: v0r3mk7cb4x3
name: Some Reports of Grafana Not Loading.
impact: major
systems:
    - hbqgpzmf8h9k
    - qqj6ssvvsqmq
    - m7cr9xxllhpn
    - jky8f03q6zfj
timeline:
    - ts: "2026-07-15 18:07:30"
      description: We are currently investigating an issue impacting a small subset of stacks in the impacted regions. We will provide more details as they become available.
      investigating: true
    - ts: "2026-07-15 18:47:38"
      description: We believe we have found the cause and are working on remediation. It is also worth mentioning that only stacks on the "slow" release channel are impacted.
