version: incident/v1
id: v44gbjl0610f
name: Delayed Aggregated Metrics (prod-us-central-0)
impact: minor
systems:
    - 1tt4gx4t4q87
timeline:
    - ts: "2026-07-15 19:19:13"
      description: "We are currently investigating a delay in aggregated metric results for tenants using Adaptive Metrics in the prod-us-central-0 region. \n\nOur engineering team has identified the issue and is actively working on a mitigation. We will provide further updates as the investigation progresses."
    - ts: "2026-07-15 21:23:23"
      description: "We have applied the mitigation and are monitoring as the backlog catches up. We will post another update once that is complete. \n\nThank you for your patience."
    - ts: "2026-07-16 03:54:19"
      description: This incident has been resolved.
      resolved: true
