version: incident/v1
id: vrhvqd6d7wqy
name: Availability issue for Grafana Cloud stacks in prod-eu-west-2 region.
impact: major
systems:
    - 6wgslg1s3bzr
timeline:
    - ts: "2024-12-11 10:28:37"
      description: We are currently investigating an issue impacting the availability of Grafana Cloud instances in the prod-eu-west-2 region.
      investigating: true
