version: incident/v1
id: vv28z7k80bjq
name: 'Synthetic Monitoring: Some Check Creations & Updates Might be Blocked.'
impact: none
systems: []
timeline:
    - ts: "2026-03-31 14:32:44"
      description: |-
        This is a retroactive status page linked to the following incident: https://status.grafana.com/incidents/38wwbz50ggrp

        This retroactive status page is meant to clarify the time of impact. This issue first started at ~2026-03-30 18:00 UTC.

        This is now resolved
      resolved: true
