version: incident/v1
id: x2pfxsnfgdq3
name: Metrics Aggregation - Degraded Performance
impact: minor
systems:
    - jhc34sjt42wd
timeline:
    - ts: "2025-09-12 18:51:43"
      description: |-
        As of 16:00 UTC, we became aware of an issue with a metrics aggregation. Users impacted may encounter metrics aggregation delays/degraded performance.

        Engineering is actively engaged and assessing the issue. We will provide updates accordingly.
      investigating: true
    - ts: "2025-09-13 00:01:03"
      description: This incident has been resolved.
      resolved: true
