version: incident/v1
id: xg2h8ht1d44n
name: Restrictions on Alerts & Reports for Grafana Cloud Free/Trial Users
impact: minor
systems:
    - wfc1hb7m917l
    - wjtq7dhjcyrm
    - 9zgd4n4s874v
    - 6p5vk5f6rx2k
    - zvfc1jlr92kg
    - tzt37d0skmyd
    - 6wgslg1s3bzr
    - qnfgxdpw26sw
    - wdcnfc3drb8s
    - z19pj782t1x2
    - 3pxb2s9gd3qk
    - 2vj35rbpdr7s
    - ggbpwgk90fsf
    - nrv6vyr5l7m8
    - 0y4zgt70mcc2
    - hl40gbs2zkn4
    - y8p2jm7hpwy0
    - y2fvl0w81hnk
    - tv6d4zqb6nz7
    - hcj5p68bp2kc
    - hbqgpzmf8h9k
    - 95tmjrzs9h1f
    - t0592d5sxhgh
    - kckd7qfk2gql
    - 8wq97lhx59x7
    - dzw0w3t3gt3y
    - 8ycwcfl7gk6r
    - v2sp8gjnhwk6
    - 2xrvqwtmgk1j
    - lxb7122px698
    - f072zpmfqxhf
    - b562z2mrff79
    - fs80tlfpb7kx
    - zljxmjgrpj4q
    - n1jdxm9d6yxp
    - h1t1253xs6k9
    - 1mnpb5g27m21
    - z8vdj0jttj7s
    - sc8qqdx6j1h5
    - 46jslxh7dbr1
    - c66zgq8xld33
    - 6lyq8vngbrgw
    - kw9wxv34yw80
    - qr8ttrr50lnd
    - bh5f9ggjnj60
    - 5n2wz8bkz9b6
    - 54tht9mpb5sk
    - 4vcmfvslpghq
    - yt6pjkj14lvk
    - cjh7n4pgpzhn
    - qqj6ssvvsqmq
    - 33nzwl8kffd6
    - hzw0yd89s9ny
    - m7cr9xxllhpn
    - fgtp31zqpw8v
    - jky8f03q6zfj
    - 2yn7w8rnphcp
    - 2cc4g3q2g0xn
    - 2fvfdmcnplg5
    - 57jn84fvz98t
    - vcm0cw90htxx
    - bvbh2cdx84ww
    - 65sdf5lsflql
    - k6ywy2zqz7fn
    - vcfc8qc5zj9n
    - 23wmy7zb3076
    - tpvdjr2xyb7x
    - y5ymzvw0c99f
    - bkkn21bgy3c4
    - 3q70xrw38s7y
    - p932bbpwynd4
    - lykc1jl88zz3
    - jw3c386xwr40
    - tgt3hljzszy8
    - v0xq65xvldk8
    - d9g9gg8d9yyl
    - tfcmnh8pbnh9
    - 42bjhxc1h49y
    - zm76x8lqb4rk
    - hd6qyr8hc0yt
    - fjr5y6v3qvx4
    - dx4hj364b8sj
    - 5shpb4hb9xd1
    - 7vr04qdqjtn6
    - 062dycqds9gm
    - ybvy0jrqz78d
    - xkjgscz19z6c
    - qjwn7tbhdl8y
    - x2sf2zvf07cy
    - lv9z30y5w7lm
timeline:
    - ts: "2026-04-20 21:12:52"
      description: Grafana Labs is taking steps to safeguard our Grafana Cloud platform against unauthorized use while maintaining the Grafana Cloud Free and Trial tiers of service our users and the community have come to rely on. As of Monday April 20, alerting and reporting capabilities have been disabled in new Grafana Cloud Free and trial stacks. We are working towards deploying improvements and restoring those functionalities in a way that keeps our platform secure and open for all of our users.
    - ts: "2026-04-20 22:07:54"
      description: We are continuing to monitor for any further issues.
    - ts: "2026-04-22 15:03:30"
      description: "Grafana Labs is implementing measures to safeguard the Grafana Cloud platform against ongoing unauthorized use while preserving the capabilities relied upon by our community. Effective immediately, we have made the following modifications to the platform:\n\nAlerting\nEmail alerting has been disabled for new Grafana Cloud Free and Trial accounts; however, all other integrations such as webhooks remain functional. Additionally, Cloud Alertmanager is now disabled for Grafana instances in these accounts, requiring all configuration to occur via the native Grafana Alertmanager. Existing Grafana Cloud accounts remain unaffected by these restrictions and all other Grafana Cloud account types are also unaffected. \n\nReporting\nTo prevent the distribution of unauthorized emails, Grafana instances in new Grafana Cloud Free and Trial accounts are limited to sending reports exclusively to users within their Grafana instance. Standard reporting functionality continues unrestricted for existing Grafana Cloud accounts and all other Grafana Cloud account types.\n\nWe remain committed to further refining platform security to ensure a safe and open environment for our entire user base."
