name: Migration cron

on:
  schedule:
    # Every hour.
    - cron: "*/15 * * * *"

permissions:
  contents: write

concurrency:
  group: "migrate"
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }} # We need to use a PAT, so pushes from this workflow execute github actions too.

      - name: Install Stactus
        run: |
          # Create container from image.
          container_id=$(docker create docker.io/slok/stactus:15f6447-amd64)

          # Extract binary from container.
          docker cp ${container_id}:/usr/local/bin/stactus /tmp/stactus
          docker rm ${container_id}

      - name: Migrate showcases
        run: /tmp/stactus showcase migrate -o ./showcases

      - name: Commit new changes.
        uses: EndBug/add-and-commit@v9
        with:
          add: ./showcases
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
