name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "migrate"
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Stactus
        run: |
          # Create container from image.
          container_id=$(docker create docker.io/slok/stactus:dd6567a-amd64)

          # Extract binary from container.
          docker cp ${container_id}:/usr/local/bin/stactus /tmp/stactus
          docker rm ${container_id}

      - name: Migrate showcases
        run: /tmp/stactus showcase migrate -o ./showcases

      - name: Commit new changes.
        uses: EndBug/add-and-commit@v9
        with:
          add: ./showcases
